# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 207d0a39ecaed2e1e014a0a4e3cd98de62d7cdc13010a8f0cee9cd895e70b832ed4a0405b87350b2b204a5c2c1c0d202a1e566473276b8890db8993f46189017

test:
  secret_key_base: 7f4b99d5e2f13a6e73f22b1ee928b69a32ed71436fb715bd78a2bd19d450456e6f51e3fbc1bac36fae901df21008c6ac8eef8b1b1119291f4600c584407e8d20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
